"""empty message

Revision ID: 41234d9a2ad3
Revises: 5333aee48a09
Create Date: 2019-03-20 17:51:51.559236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41234d9a2ad3'
down_revision = '5333aee48a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preset_story_title', table_name='preset_story')
    op.create_index(op.f('ix_preset_story_title'), 'preset_story', ['title'], unique=False)
    op.drop_constraint('preset_story_content_key', 'preset_story', type_='unique')
    op.add_column('user_stories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_user_stories_title', table_name='user_stories')
    op.create_index(op.f('ix_user_stories_title'), 'user_stories', ['title'], unique=False)
    op.drop_constraint('user_stories_content_key', 'user_stories', type_='unique')
    op.create_foreign_key(None, 'user_stories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stories', type_='foreignkey')
    op.create_unique_constraint('user_stories_content_key', 'user_stories', ['content'])
    op.drop_index(op.f('ix_user_stories_title'), table_name='user_stories')
    op.create_index('ix_user_stories_title', 'user_stories', ['title'], unique=True)
    op.drop_column('user_stories', 'user_id')
    op.create_unique_constraint('preset_story_content_key', 'preset_story', ['content'])
    op.drop_index(op.f('ix_preset_story_title'), table_name='preset_story')
    op.create_index('ix_preset_story_title', 'preset_story', ['title'], unique=True)
    # ### end Alembic commands ###
