"""empty message

Revision ID: 5333aee48a09
Revises: d5fdc676d153
Create Date: 2019-03-19 10:27:47.001109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5333aee48a09'
down_revision = 'd5fdc676d153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preset_story', 'content',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.alter_column('user_stories', 'content',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stories', 'content',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('preset_story', 'content',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
