"""empty message

Revision ID: d5fdc676d153
Revises: 1580c02796d4
Create Date: 2019-03-19 09:53:51.867169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fdc676d153'
down_revision = '1580c02796d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset_story', sa.Column('prompts', sa.String(length=5000), nullable=True))
    op.add_column('user_stories', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stories', 'date_created')
    op.drop_column('preset_story', 'prompts')
    # ### end Alembic commands ###
